learning_logs/urls.py
"""Defines URL patterns for learning_logs."""
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
	path('', views.index, name="index"),
	# url(r'^$', views.index, name"index"),
	# show all topics
	path('topics/', views.topics, name="topics"),
	# url(r'^topics/$', views.topics, name="topics"),
	# Detail page for single topic
	path('topics/<int:topic_id>/', views.topic, name="topic"),
	# url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name="topic"),
	# Form page for new topic.
	path('new_topic/', views.new_topic, name="new_topic"),
	# url(r'^new_topic/$', views.new_topic, name="new_topic"),
	# Page for adding a new Entry.
	path('new_entry/<int:topic_id>/', views.new_entry, name="new_entry"),
	# url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name="new_entry"),
	# Page for editing an Entry.
	path('edit_entry/<int:entry_id>/', views.edit_entry, name="edit_entry"),
	# url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name="edit_entry"),
]

pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView

urlpatterns = [
    path('home/', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
]

pages_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls')),
    path('', include('learning_logs.urls')),
    path('pizzas/', include('pizzas.urls')),
    path('users/', include('users.urls')),
]

pizzas/urls.py
"""Defines URL patterns for pizzas app."""
from django.urls import path
from . import views

app_name='pizzas'

urlpatterns = [
	path('', views.index, name='index'),
	# Lists of the Pizza Types.
	path('pizzas/', views.pizzas, name='pizzas'),
	# Details of a Pizza Type.
	path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
	# Add new Pizza Type
	path('add_pizza/', views.add_pizza, name='add_pizza'),
	# Add new topping in a Pizza-Type
	path('add_topping/<int:pizza_id>/', views.add_topping, name='add_topping'),
	# Edit the Toppings Details.
	path('edit_topping/<int:topping_id>/', views.edit_topping, name='edit_topping'),
]

users/urls.py
"""Defines URL patterns for Users."""
from django.urls import path, include
# from django.contrib.auth.views import login

from . import views

app_name = 'users'
urlpatterns = [
	# Login Page
	# path('login/', login, {'template_name': 'users/login.html'}, name='login'),

	path('logout/', views.logout_view, name='logout_view'),
	path('account/', include('django.contrib.auth.urls')),
	path('register/', views.register, name='register'),

]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
	"""a Topic the user is learning about."""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE,)


	def __str__(self):
		"""return a string representation of the model."""
		return self.text


class Entry(models.Model):
	"""something specific learnt about the Topic."""
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE,)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)


	class Meta:
		verbose_name_plural = 'entries'


	def __str__(self):
		"""return a string representation of the models."""
		if len(self.text)>50:
			return self.text[:50] + "..."
		else:
			return self.text

learning_logs/forms.py
from django import forms
# from django.forms import ModelForm
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
# class TopicForm(ModelForm):
	"""docstring for TopicForm"""
	class Meta:
		"""docstring for Meta"""
		model = Topic
		fields = [
			'text',
			]
		labels = {
			'text': 'Enter your Topic',
			}


class EntryForm(forms.ModelForm):
	"""docstring for EntryForm"""
	class Meta:
		"""docstring for Meta"""
		model = Entry
		fields = [
			'text',
		]
		labels = {
			# 'text': 'Enter you learning details',
			'text': '',
		}
		widgets = {
			'text': forms.Textarea(
				attrs={
					'cols': 80,
				}
			)
		}

learning_logs/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, Http404
# from django.core.urlresolvers import reverse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def check_topic_owner(topic_owner, request_user):
	"""Checks if request user matches with topic owner."""
	if topic_owner != request_user:
		raise Http404


def index(request):
	"""The home page for learning logs."""
	return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
	"""Show all topics."""
	# topics = Topic.objects.order_by('date_added')
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')
	context = {
		'topics': topics,
	}
	return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
	"""Show a single Topic and all its Entries."""
	topic = Topic.objects.get(id=topic_id)
	
	check_topic_owner(topic.owner, request.user)

	entries = topic.entry_set.order_by('-date_added')
	context = {
		'topic': topic,
		'entries': entries,
	}
	return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
	"""Add a new Topic."""
	if request.method != 'POST':
		# No data submitted, create a blank Form
		form = TopicForm()
	else:
		# POST data submitted, process data.
		form = TopicForm(request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return HttpResponseRedirect(reverse('learning_logs:topics'))
			# return HttpResponseRedirect('learning_logs/topics')
			# return redirect('learning_logs/topics')
	
	context = {'form': form}
	return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
	"""Add a new Entry for a particular Topic."""
	topic = Topic.objects.get(id=topic_id)
	if request.method != 'POST':
		# No data submitted. Create an Empty form.
		form = EntryForm()
	else:
		# POST data submitted. process data.
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id,]))

	context = {
		'topic': topic,
		'form': form,
	}
	return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
	"""Edit an existing Entry."""
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic

	check_topic_owner(topic.owner, request.user)

	# if topic.owner != request.user:
	# 	raise Http404

	if request.method != 'POST':
		form = EntryForm(instance=entry)

	else:
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id,]))

	context = {
		'entry': entry,
		'topic': topic,
		'form': form,
	}
	return render(request, 'learning_logs/edit_entry.html', context)

templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=divice-width, initial-scale=1">

	<title>Learning Logs</title>

	{% bootstrap_css %}
	{% bootstrap_javascript %}

</head>
<body>
	<!-- Static Navbar -->
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" area-expanded="false" area-controls="navbar"></button>
				<a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Logs</a>
			</div>

			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
					<li><a href="{% url 'pizzas:index' %}">Pizzas</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
						<li><a>{{ user.username.title }}</a></li>
						<li><a href="{% url 'users:logout_view' %}">LogOut</a></li>
					{% else %}
						<li><a href="{% url 'users:register' %}">Register</a></li>
						<li><a href="{% url 'users:login' %}">LogIn</a></li>
					{% endif %}
				</ul>
			</div> <!--/.nav-collapse -->
		</div>
	</nav>

	<div class="container">
		<div class="page-header">
			{% block header %}{% endblock header %}
		</div>
		<div>
			{% block content %}{% endblock content %}
		</div>
	</div><!-- /container -->

</body>
</html>

<!-- <p>
	<h2>
		<a href="{% url 'learning_logs:index' %}">Learining Log</a> - 
		<a href="{% url 'learning_logs:topics' %}">Topics</a> - 
		<a href="{% url 'pizzas:index' %}">Pizzas</a> - 

		{% if user.is_authenticated %}
			{{ user.username.title }}
			<a href="{% url 'users:logout_view' %}">LogOut</a>
		{% else %}
			<a href="{% url 'users:register' %}">Register</a> - 
			<a href="{% url 'users:login' %}">LogIn</a>
		{% endif %}
	</h2>
</p>
 -->

templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}

	<h3>
		<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
	</h3>
	<h4>Edit Entry: </h4>
	<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='POST'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Save</button>
	</form>

{% endblock content %}

templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block header %}
	<div class="jumbotron">
		<h3>Track Your Learning</h3>
	</div>
{% endblock header %}

{% block content %}
	<h4>
		<a href="{% url 'users:register' %}">Register an account</a> to make your own learning log, and list the topics you're learining about.
	</h4>
	<h4>
		Whenever you learn something new about a topic, make an entry summarizing what you've learned.
	</h4>
	<!-- <p>Learning Log</p>
	<p>Learning logs helps you keep track of your learning, for any topic you are learning about.</p> -->
{% endblock content %}

templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}

	<h3>
		<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
	</h3>

	<p>Add your New Learning: </p>
	<form action="{% url 'learning_logs:new_entry' topic.id %}", method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="Submit">Add</button>
	</form>

{% endblock content %}

templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

	<h3>Add a New Topic:</h3>

	<form action="{% url 'learning_logs:new_topic' %}" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" name="submit" value="Create">
	</form>

{% endblock content %}

templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

	<h3>Topic: {{ topic }} | author: {{ topic.owner }}</h3>

	<h4>Entries: | <a href="{% url 'learning_logs:new_entry' topic.id %}">Add New Entry</a></h4>
	<ol>
		{% for entry in entries %}
			<li>
			 	<p>{{ entry.text|linebreaks }}</p>
			 	<p>
			 		<b>Date: </b>{{ entry.date_added }} | 
			 		<b>{{ topic.owner }}</b>
			 		<strong> | 
			 			<a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit</a>
			 		</strong>
			 	</p>
			</li>
		{% empty %}
			<p>There's no entry for this post yet.</p>
		{% endfor %}
	</ol>

{% endblock content %}

templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}

	<h3>Topics | <a href="{% url 'learning_logs:new_topic' %}">Create</a></h3>

	<ul>
		{% for topic in topics %}
			<li>
				<strong>
					<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
				</strong>
			</li>
		{% empty %}
			<li>No Topic has been added yet.</li>
		{% endfor %}
	</ul>

{% endblock content %}