learning_logs/urls.py
"""Defines URL patterns for learning_logs."""
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
	path('', views.index, name="index"),
	# url(r'^$', views.index, name"index"),
	# show all topics
	path('topics/', views.topics, name="topics"),
	# url(r'^topics/$', views.topics, name="topics"),
	# Detail page for single topic
	path('topics/<int:topic_id>/', views.topic, name="topic"),
	# url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name="topic"),
	# Form page for new topic.
	path('new_topic/', views.new_topic, name="new_topic"),
	# url(r'^new_topic/$', views.new_topic, name="new_topic"),
	# Page for adding a new Entry.
	path('new_entry/<int:topic_id>/', views.new_entry, name="new_entry"),
	# url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name="new_entry"),
	# Page for editing an Entry.
	path('edit_entry/<int:entry_id>/', views.edit_entry, name="edit_entry"),
	# url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name="edit_entry"),
]

pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView

urlpatterns = [
    path('home/', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
]

pages_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls')),
    path('', include('learning_logs.urls')),
    path('pizzas/', include('pizzas.urls')),
    path('users/', include('users.urls')),
]

pizzas/urls.py
"""Defines URL patterns for pizzas app."""
from django.urls import path
from . import views

app_name='pizzas'

urlpatterns = [
	path('', views.index, name='index'),
	# Lists of the Pizza Types.
	path('pizzas/', views.pizzas, name='pizzas'),
	# Details of a Pizza Type.
	path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
	# Add new Pizza Type
	path('add_pizza/', views.add_pizza, name='add_pizza'),
	# Add new topping in a Pizza-Type
	path('add_topping/<int:pizza_id>/', views.add_topping, name='add_topping'),
	# Edit the Toppings Details.
	path('edit_topping/<int:topping_id>/', views.edit_topping, name='edit_topping'),
]

pizzas/models.py
from django.db import models
from django.contrib.auth.models import User


class Pizza(models.Model):
	"""a name of the pizza the user likes."""
	name = models.CharField(max_length=50)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE,)

	def __str__(self):
		"""return a string representation of model."""
		return self.name.title()


class Topping(models.Model):
	"""a name of topping the user favours on pizza."""
	pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE,)
	name = models.CharField(max_length=70)
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		"""docstring for Meta"""
		verbose_name_plural = "toppings"


	def __str__(self):
		"""returns a string representation of model."""
		return self.name.title()

pizzas/forms.py
from django.forms import ModelForm

from .models import Pizza,Topping


class PizzaForm(ModelForm):
	"""docstring for ClassName"""
	class Meta:
		"""docstring for Meta"""
		model = Pizza
		fields = ['name',]
		labels = {
			'name': 'Enter Name: '
		}
	

class ToppingForm(ModelForm):
	"""docstring for ToppingForm"""
	class Meta:
		"""docstring for Meta"""
		model = Topping
		fields = ['name',]
		labels = {
			'name': 'Enter Name '
		}

pizzas/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Pizza, Topping
from .forms import PizzaForm, ToppingForm


def index(request):
	return render(request, 'pizzas/index.html')


@login_required
def pizzas(request):
	pizzas = Pizza.objects.order_by('id')
	context = {
		'pizzas': pizzas
	}
	return render(request, 'pizzas/pizzas.html', context)


@login_required
def pizza(request, pizza_id):
	"""Show a single Pizza type and all its Toppings."""
	pizza = Pizza.objects.get(id=pizza_id)
	toppings = pizza.topping_set.order_by('-date_added')
	context = {
		'pizza': pizza,
		'toppings': toppings,
	}
	return render(request, 'pizzas/pizza.html', context)


@login_required
def add_pizza(request):
	"""Add new Pizza type."""
	if request.method != 'POST':
		form = PizzaForm()
	else:
		form = PizzaForm(data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('pizzas:pizzas'))
	context = {
		'form': form,
	}
	return render(request, 'pizzas/new_pizza.html', context)


@login_required
def add_topping(request, pizza_id):
	"""Add new topping on you favourite Pizza."""
	pizza = Pizza.objects.get(id=pizza_id)

	if request.method != 'POST':
		form = ToppingForm()
	else:
		form = ToppingForm(data=request.POST)
		if form.is_valid():
			new_topping = form.save(commit=False)
			new_topping.pizza = pizza
			new_topping.save()
			print('data saved!!')
			return HttpResponseRedirect(reverse('pizzas:pizza', args=[pizza_id,]))

	context = {
		'pizza': pizza,
		'form': form,
	}
	return render(request, 'pizzas/new_topping.html', context)


@login_required
def edit_topping(request, topping_id):
	"""Edit the related Topping details."""
	topping = Topping.objects.get(id=topping_id)
	pizza = topping.pizza

	if request.method != 'POST':
		form = ToppingForm(instance=topping)
	else:
		form = ToppingForm(instance=topping, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('pizzas:pizza', args=[pizza.id,]))

	context={
		'topping': topping,
		'pizza': pizza,
		'form': form,
	}
	return render(request, 'pizzas/edit_topping.html', context)

templates/pizzas/base.html
<h2>
	<a href="{% url 'pizzas:index' %}">Pizzas Logs</a> - 
	<a href="{% url 'pizzas:pizzas' %}">Pizzas</a> - 
	<a href="{% url 'learning_logs:index' %}">Learning Logs</a>

</h2>

{% block content %}{% endblock content %}

templates/pizzas/edit_topping.html
{% extends 'pizzas/base.html' %}

{% block content %}
	<h3>
		<a href="{% url 'pizzas:pizza' pizza.id %}">Pizza</a>
	</h3>

	<h4>Edit Topping:</h4>
	<form action="{% url 'pizzas:edit_topping' topping.id %}" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Edit</button>
	</form>

{% endblock content %}

templates/pizzas/index.html
{% extends 'pizzas/base.html' %}

{% block content %}
	<p>Pizza List</p>
	<p>Here we list out your favourite pizza with toppings.</p>
{% endblock content %}

templates/pizzas/new_pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}
	<h4>Add your new Pizza Type: </h4>
	<form action="{% url 'pizzas:add_pizza' %}", method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" name="submit" value="Add">
	</form>
{% endblock content %}

templates/pizzas/new_topping.html
{% extends 'pizzas/base.html' %}

{% block content %}

	<h3>
		<a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
	</h3>
	<p>Add new Topping: </p>

	<form action="{% url 'pizzas:add_topping' pizza.id %}" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Add</button>
	</form>
{% endblock content %}

templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}
	<h3>{{ pizza.id}}. {{ pizza }}</h3>

	<h4>Toppings: | <a href="{% url 'pizzas:add_topping' pizza.id %}">Add</a></h4>
	<ol>
		{% for topping in toppings %}
			<li>
				<strong>
					<p>{{ topping.name.title }}</p>
				</strong>
				<p>Date: {{ topping.date_added }} | 
					<strong>
						<a href="{% url 'pizzas:edit_topping' topping.id %}">Edit</a>
					</strong>
				</p>
			</li>
		{% empty %}
			<p>You have no Topping entries. Make some entries.</p>
		{% endfor %}
	</ol>
	
{% endblock content %}

templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %}

{% block content %}
	<h3>Pizza List: | <a href="{% url 'pizzas:add_pizza' %}">Add</a></h3>
	<ol>
		{% for pizza in pizzas %}
			<strong>
				<li><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></li>
			</strong>
		{% empty %}
			<p>No Data on Pizza. Add some Pizzas.</p>
		{% endfor %}
	</ol>

{% endblock content %}